# goshell.toml config file
# goshell 0.1 version
[init]
scripts = ["/home/camilo/.local/bin/unix"]

[theme]
prompt = "dmr  "
colors = "#DE8F78"

[[alias]]
alias = "ll"
command = "exa --icons -al --sort=type"

[[alias]]
alias = "z"
command = "zd"
